
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.1.0.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace GitCommander {
    using System;
    using Terminal.Gui;
    
    
    public partial class MyView : Terminal.Gui.Window {
        
        private Terminal.Gui.ColorScheme greenOnBlack;
        
        private Terminal.Gui.View prListView;
        
        private Terminal.Gui.View view2;
        
        private Terminal.Gui.Button fetchPrBtn;
        
        private void InitializeComponent() {
            this.fetchPrBtn = new Terminal.Gui.Button();
            this.view2 = new Terminal.Gui.View();
            this.prListView = new Terminal.Gui.View();
            this.greenOnBlack = new Terminal.Gui.ColorScheme();
            this.greenOnBlack.Normal = new Terminal.Gui.Attribute(Terminal.Gui.Color.Green, Terminal.Gui.Color.Black);
            this.greenOnBlack.HotNormal = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightGreen, Terminal.Gui.Color.Black);
            this.greenOnBlack.Focus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Green, Terminal.Gui.Color.Magenta);
            this.greenOnBlack.HotFocus = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightGreen, Terminal.Gui.Color.Magenta);
            this.greenOnBlack.Disabled = new Terminal.Gui.Attribute(Terminal.Gui.Color.Gray, Terminal.Gui.Color.Black);
            this.Width = Dim.Fill(0);
            this.Height = Dim.Fill(0);
            this.X = 0;
            this.Y = 0;
            this.Visible = true;
            this.Modal = false;
            this.IsMdiContainer = false;
            this.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this.Border.Effect3D = false;
            this.Border.Effect3DBrush = null;
            this.Border.DrawMarginFrame = true;
            this.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Title = "";
            this.prListView.Width = Dim.Percent(50f);
            this.prListView.Height = Dim.Percent(100f);
            this.prListView.X = 0;
            this.prListView.Y = 0;
            this.prListView.Visible = true;
            this.prListView.Data = "prListView";
            this.prListView.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.prListView);
            this.view2.Width = Dim.Percent(50f);
            this.view2.Height = Dim.Percent(95f);
            this.view2.X = Pos.Right(prListView);
            this.view2.Y = 0;
            this.view2.Visible = true;
            this.view2.Data = "view2";
            this.view2.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.view2);
            this.fetchPrBtn.Width = 21;
            this.fetchPrBtn.Height = 1;
            this.fetchPrBtn.X = 96;
            this.fetchPrBtn.Y = 26;
            this.fetchPrBtn.Visible = true;
            this.fetchPrBtn.Data = "fetchPrBtn";
            this.fetchPrBtn.Text = "Fetch List of PRs";
            this.fetchPrBtn.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.fetchPrBtn.IsDefault = false;
            this.Add(this.fetchPrBtn);
        }
    }
}
