
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.1.0.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace GitCommander {
    using System;
    using Terminal.Gui;
    
    
    public partial class MyView : Terminal.Gui.Window {
        
        private Terminal.Gui.ColorScheme greenOnBlack;
        
        private Terminal.Gui.View view;
        
        private Terminal.Gui.ScrollView scrollView;
        
        private Terminal.Gui.ListView listView;
        
        private Terminal.Gui.Button button;
        
        private void InitializeComponent() {
            this.button = new Terminal.Gui.Button();
            this.listView = new Terminal.Gui.ListView();
            this.scrollView = new Terminal.Gui.ScrollView();
            this.view = new Terminal.Gui.View();
            this.greenOnBlack = new Terminal.Gui.ColorScheme();
            this.greenOnBlack.Normal = new Terminal.Gui.Attribute(Terminal.Gui.Color.Green, Terminal.Gui.Color.Black);
            this.greenOnBlack.HotNormal = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightGreen, Terminal.Gui.Color.Black);
            this.greenOnBlack.Focus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Green, Terminal.Gui.Color.Magenta);
            this.greenOnBlack.HotFocus = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightGreen, Terminal.Gui.Color.Magenta);
            this.greenOnBlack.Disabled = new Terminal.Gui.Attribute(Terminal.Gui.Color.Gray, Terminal.Gui.Color.Black);
            this.Width = Dim.Fill(0);
            this.Height = Dim.Fill(0);
            this.X = 0;
            this.Y = 0;
            this.Visible = true;
            this.Modal = false;
            this.IsMdiContainer = false;
            this.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this.Border.Effect3D = false;
            this.Border.Effect3DBrush = null;
            this.Border.DrawMarginFrame = true;
            this.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Title = "";
            this.view.Width = Dim.Fill(118);
            this.view.Height = Dim.Fill(28);
            this.view.X = 0;
            this.view.Y = 0;
            this.view.Visible = true;
            this.view.ColorScheme = this.greenOnBlack;
            this.view.Data = "view";
            this.view.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.view);
            this.scrollView.Width = Dim.Percent(50f);
            this.scrollView.Height = Dim.Percent(100f);
            this.scrollView.X = 0;
            this.scrollView.Y = 0;
            this.scrollView.Visible = true;
            this.scrollView.ContentSize = new Size(20,10);
            this.scrollView.Data = "scrollView";
            this.scrollView.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.scrollView);
            this.listView.Width = 20;
            this.listView.Height = 3;
            this.listView.X = 1;
            this.listView.Y = 1;
            this.listView.Visible = true;
            this.listView.Data = "listView";
            this.listView.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.listView.Source = new Terminal.Gui.ListWrapper(new string[] {
                        "Item1",
                        "Item2",
                        "Item3"});
            this.listView.AllowsMarking = false;
            this.listView.AllowsMultipleSelection = true;
            this.scrollView.Add(this.listView);
            this.button.Width = 21;
            this.button.Height = 1;
            this.button.X = 63;
            this.button.Y = 27;
            this.button.Visible = true;
            this.button.Data = "button";
            this.button.Text = "Fetch List of PRs";
            this.button.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.button.IsDefault = false;
            this.Add(this.button);
        }
    }
}
