//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.1.0.0
//      You can make changes to this file and they will not be overwritten when saving.
//  </auto-generated>
// -----------------------------------------------------------------------------

using GitCommander.Models;
using Octokit;
using Tomlyn;

namespace GitCommander
{
    using Terminal.Gui;


    public partial class MyView
    {
        public MyView()
        {
            var tomlText = File.ReadAllText("Config.toml");
            var config = Toml.ToModel<Config>(tomlText);
            var token = config.Token.Value;
            InitializeComponent();
            var repos = config.Repos;

            var github = new GitHubClient(new ProductHeaderValue("GitCommander"))
            {
                Credentials = new Credentials(token)
            };
            var scrollviews = new List<View>();
            var count = 0;
            foreach (var repo in repos)
            {
                var infovi =
                    github.PullRequest.GetAllForRepository(repo.User, repo.Name).Result.Select(x => $"{x.Title}  - {x.User.Login} -  {x.State}");
                var v = new PrListView(infovi);
                v.Height = Dim.Percent(50f);
                scrollviews.Add(v);
            }

            for (int i = 0; i < scrollviews.Count; i++)
            {
                if (i !=  0)
                {
                    Console.WriteLine(i);
                    scrollviews[i].Y = Pos.Bottom(scrollviews[i - 1]);
                }
                else
                {
                    scrollviews[i].Y = 0;
                }
                prListView.Add(scrollviews[i]);
            }
        }
    }
}