
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.1.0.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace GitCommander {
    using System;
    using Terminal.Gui;
    
    
    public partial class MyView : Terminal.Gui.Window {
        
        private Terminal.Gui.ColorScheme greenOnBlack;
        
        private Terminal.Gui.View view;
        
        private Terminal.Gui.ScrollView prListScV;
        
        private Terminal.Gui.Label repoLbl;
        
        private Terminal.Gui.ListView prList;
        
        private Terminal.Gui.Label label2;
        
        private Terminal.Gui.ListView repoList;
        
        private Terminal.Gui.Button fetchPrBtn;
        
        private void InitializeComponent() {
            this.fetchPrBtn = new Terminal.Gui.Button();
            this.repoList = new Terminal.Gui.ListView();
            this.label2 = new Terminal.Gui.Label();
            this.prList = new Terminal.Gui.ListView();
            this.repoLbl = new Terminal.Gui.Label();
            this.prListScV = new Terminal.Gui.ScrollView();
            this.view = new Terminal.Gui.View();
            this.greenOnBlack = new Terminal.Gui.ColorScheme();
            this.greenOnBlack.Normal = new Terminal.Gui.Attribute(Terminal.Gui.Color.Green, Terminal.Gui.Color.Black);
            this.greenOnBlack.HotNormal = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightGreen, Terminal.Gui.Color.Black);
            this.greenOnBlack.Focus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Green, Terminal.Gui.Color.Magenta);
            this.greenOnBlack.HotFocus = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightGreen, Terminal.Gui.Color.Magenta);
            this.greenOnBlack.Disabled = new Terminal.Gui.Attribute(Terminal.Gui.Color.Gray, Terminal.Gui.Color.Black);
            this.Width = Dim.Fill(0);
            this.Height = Dim.Fill(0);
            this.X = 0;
            this.Y = 0;
            this.Visible = true;
            this.Modal = false;
            this.IsMdiContainer = false;
            this.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this.Border.Effect3D = false;
            this.Border.Effect3DBrush = null;
            this.Border.DrawMarginFrame = true;
            this.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Title = "";
            this.view.Width = Dim.Fill(118);
            this.view.Height = Dim.Fill(28);
            this.view.X = 0;
            this.view.Y = 0;
            this.view.Visible = true;
            this.view.ColorScheme = this.greenOnBlack;
            this.view.Data = "view";
            this.view.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.view);
            this.prListScV.Width = Dim.Percent(50f);
            this.prListScV.Height = Dim.Percent(50f);
            this.prListScV.X = 0;
            this.prListScV.Y = 0;
            this.prListScV.Visible = true;
            this.prListScV.ContentSize = new Size(20,10);
            this.prListScV.Data = "prListScV";
            this.prListScV.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.prListScV);
            this.repoLbl.Width = 4;
            this.repoLbl.Height = 1;
            this.repoLbl.X = 0;
            this.repoLbl.Y = 0;
            this.repoLbl.Visible = true;
            this.repoLbl.Data = "repoLbl";
            this.repoLbl.Text = "Repository";
            this.repoLbl.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.prListScV.Add(this.repoLbl);
            this.prList.Width = 20;
            this.prList.Height = 3;
            this.prList.X = 1;
            this.prList.Y = 1;
            this.prList.Visible = true;
            this.prList.Data = "prList";
            this.prList.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.prList.Source = new Terminal.Gui.ListWrapper(new string[] {
                        "Item1",
                        "Item2",
                        "Item3"});
            this.prList.AllowsMarking = false;
            this.prList.AllowsMultipleSelection = true;
            this.prListScV.Add(this.prList);
            this.label2.Width = 3;
            this.label2.Height = 1;
            this.label2.X = 63;
            this.label2.Y = 1;
            this.label2.Visible = true;
            this.label2.Data = "label2";
            this.label2.Text = "List of Repositories watching";
            this.label2.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.label2);
            this.repoList.Width = 20;
            this.repoList.Height = 3;
            this.repoList.X = 63;
            this.repoList.Y = 3;
            this.repoList.Visible = true;
            this.repoList.Data = "repoList";
            this.repoList.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.repoList.Source = new Terminal.Gui.ListWrapper(new string[] {
                        "Item1",
                        "Item2",
                        "Item3"});
            this.repoList.AllowsMarking = false;
            this.repoList.AllowsMultipleSelection = true;
            this.Add(this.repoList);
            this.fetchPrBtn.Width = 21;
            this.fetchPrBtn.Height = 1;
            this.fetchPrBtn.X = 63;
            this.fetchPrBtn.Y = 27;
            this.fetchPrBtn.Visible = true;
            this.fetchPrBtn.Data = "fetchPrBtn";
            this.fetchPrBtn.Text = "Fetch List of PRs";
            this.fetchPrBtn.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.fetchPrBtn.IsDefault = false;
            this.Add(this.fetchPrBtn);
        }
    }
}
