
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.1.0.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace GitCommander {
    using System;
    using Terminal.Gui;
    
    
    public partial class PrInfoView : Terminal.Gui.Window {
        
        private Terminal.Gui.Label prName;
        
        private Terminal.Gui.Label statusLbl;
        
        private Terminal.Gui.Label repoLbl;
        
        private void InitializeComponent() {
            this.repoLbl = new Terminal.Gui.Label();
            this.statusLbl = new Terminal.Gui.Label();
            this.prName = new Terminal.Gui.Label();
            this.Width = Dim.Fill(0);
            this.Height = Dim.Fill(0);
            this.X = 0;
            this.Y = Pos.Percent(0f);
            this.Visible = true;
            this.Modal = false;
            this.IsMdiContainer = false;
            this.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this.Border.Effect3D = false;
            this.Border.Effect3DBrush = null;
            this.Border.DrawMarginFrame = true;
            this.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Title = "";
            this.prName.Width = Dim.Percent(33f);
            this.prName.Height = 1;
            this.prName.X = 0;
            this.prName.Y = 0;
            this.prName.Visible = true;
            this.prName.Data = "prName";
            this.prName.Text = "PrName";
            this.prName.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.prName);
            this.statusLbl.Width = Dim.Percent(33f);
            this.statusLbl.Height = 1;
            this.statusLbl.X = 38;
            this.statusLbl.Y = 0;
            this.statusLbl.Visible = true;
            this.statusLbl.Data = "statusLbl";
            this.statusLbl.Text = "Status";
            this.statusLbl.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.statusLbl);
            this.repoLbl.Width = Dim.Fill(0);
            this.repoLbl.Height = Dim.Fill(1);
            this.repoLbl.X = 76;
            this.repoLbl.Y = 0;
            this.repoLbl.Visible = true;
            this.repoLbl.Data = "repoLbl";
            this.repoLbl.Text = "Repo";
            this.repoLbl.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.repoLbl);
        }
    }
}
