
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.1.0.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace GitCommander {
    using System;
    using Terminal.Gui;
    
    
    public partial class RepoView : Terminal.Gui.View {
        
        private Terminal.Gui.Label repoName;
        
        private void InitializeComponent() {
            this.repoName = new Terminal.Gui.Label();
            this.Width = Dim.Fill(0);
            this.Height = Dim.Fill(0);
            this.X = 0;
            this.Y = 0;
            this.Visible = true;
            this.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.repoName.Width = 3;
            this.repoName.Height = 1;
            this.repoName.X = 2;
            this.repoName.Y = 1;
            this.repoName.Visible = true;
            this.repoName.Data = "repoName";
            this.repoName.Text = "RepoName";
            this.repoName.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.repoName);
        }
    }
}
